// Import necessary icons from react-icons/gi
import {
  GiCardAceSpades,
  GiCardKingSpades,
  GiCardQueenSpades,
  GiCardJackSpades,
  GiCard10Spades,
  GiCard9Spades,
  GiCard8Spades,
  GiCard7Spades,
  GiCard6Spades,
  GiCard5Spades,
  GiCard4Spades,
  GiCard3Spades,
  GiCard2Spades,
  GiCardAceHearts,
  GiCardKingHearts,
  GiCardQueenHearts,
  GiCardJackHearts,
  GiCard10Hearts,
  GiCard9Hearts,
  GiCard8Hearts,
  GiCard7Hearts,
  GiCard6Hearts,
  GiCard5Hearts,
  GiCard4Hearts,
  GiCard3Hearts,
  GiCard2Hearts,
  GiCardAceDiamonds,
  GiCardKingDiamonds,
  GiCardQueenDiamonds,
  GiCardJackDiamonds,
  GiCard10Diamonds,
  GiCard9Diamonds,
  GiCard8Diamonds,
  GiCard7Diamonds,
  GiCard6Diamonds,
  GiCard5Diamonds,
  GiCard4Diamonds,
  GiCard3Diamonds,
  GiCard2Diamonds,
  GiCardAceClubs,
  GiCardKingClubs,
  GiCardQueenClubs,
  GiCardJackClubs,
  GiCard10Clubs,
  GiCard9Clubs,
  GiCard8Clubs,
  GiCard7Clubs,
  GiCard6Clubs,
  GiCard5Clubs,
  GiCard4Clubs,
  GiCard3Clubs,
  GiCard2Clubs,
} from "react-icons/gi";

export const CARD_TABLE = [
  // Spades
  { name: "Ace of Spades", shortCode: "AS", suit: "Spades", value: 1, unicode: "🂡", unicodeText: "U+1F0A1", icon: GiCardAceSpades },
  { name: "King of Spades", shortCode: "KS", suit: "Spades", value: 13, unicode: "🂮", unicodeText: "U+1F0AE", icon: GiCardKingSpades },
  { name: "Queen of Spades", shortCode: "QS", suit: "Spades", value: 12, unicode: "🂭", unicodeText: "U+1F0AD", icon: GiCardQueenSpades },
  { name: "Jack of Spades", shortCode: "JS", suit: "Spades", value: 11, unicode: "🂫", unicodeText: "U+1F0AB", icon: GiCardJackSpades },
  { name: "10 of Spades", shortCode: "10S", suit: "Spades", value: 10, unicode: "🂪", unicodeText: "U+1F0AA", icon: GiCard10Spades },
  { name: "9 of Spades", shortCode: "9S", suit: "Spades", value: 9, unicode: "🂩", unicodeText: "U+1F0A9", icon: GiCard9Spades },
  { name: "8 of Spades", shortCode: "8S", suit: "Spades", value: 8, unicode: "🂨", unicodeText: "U+1F0A8", icon: GiCard8Spades },
  { name: "7 of Spades", shortCode: "7S", suit: "Spades", value: 7, unicode: "🂧", unicodeText: "U+1F0A7", icon: GiCard7Spades },
  { name: "6 of Spades", shortCode: "6S", suit: "Spades", value: 6, unicode: "🂦", unicodeText: "U+1F0A6", icon: GiCard6Spades },
  { name: "5 of Spades", shortCode: "5S", suit: "Spades", value: 5, unicode: "🂥", unicodeText: "U+1F0A5", icon: GiCard5Spades },
  { name: "4 of Spades", shortCode: "4S", suit: "Spades", value: 4, unicode: "🂤", unicodeText: "U+1F0A4", icon: GiCard4Spades },
  { name: "3 of Spades", shortCode: "3S", suit: "Spades", value: 3, unicode: "🂣", unicodeText: "U+1F0A3", icon: GiCard3Spades },
  { name: "2 of Spades", shortCode: "2S", suit: "Spades", value: 2, unicode: "🂢", unicodeText: "U+1F0A2", icon: GiCard2Spades },

  // Hearts
  { name: "Ace of Hearts", shortCode: "AH", suit: "Hearts", value: 1, unicode: "🂱", unicodeText: "U+1F0B1", icon: GiCardAceHearts },
  { name: "King of Hearts", shortCode: "KH", suit: "Hearts", value: 13, unicode: "🂾", unicodeText: "U+1F0BE", icon: GiCardKingHearts },
  { name: "Queen of Hearts", shortCode: "QH", suit: "Hearts", value: 12, unicode: "🂽", unicodeText: "U+1F0BD", icon: GiCardQueenHearts },
  { name: "Jack of Hearts", shortCode: "JH", suit: "Hearts", value: 11, unicode: "🂻", unicodeText: "U+1F0BB", icon: GiCardJackHearts },
  { name: "10 of Hearts", shortCode: "10H", suit: "Hearts", value: 10, unicode: "🂺", unicodeText: "U+1F0BA", icon: GiCard10Hearts },
  { name: "9 of Hearts", shortCode: "9H", suit: "Hearts", value: 9, unicode: "🂹", unicodeText: "U+1F0B9", icon: GiCard9Hearts },
  { name: "8 of Hearts", shortCode: "8H", suit: "Hearts", value: 8, unicode: "🂸", unicodeText: "U+1F0B8", icon: GiCard8Hearts },
  { name: "7 of Hearts", shortCode: "7H", suit: "Hearts", value: 7, unicode: "🂷", unicodeText: "U+1F0B7", icon: GiCard7Hearts },
  { name: "6 of Hearts", shortCode: "6H", suit: "Hearts", value: 6, unicode: "🂶", unicodeText: "U+1F0B6", icon: GiCard6Hearts },
  { name: "5 of Hearts", shortCode: "5H", suit: "Hearts", value: 5, unicode: "🂵", unicodeText: "U+1F0B5", icon: GiCard5Hearts },
  { name: "4 of Hearts", shortCode: "4H", suit: "Hearts", value: 4, unicode: "🂴", unicodeText: "U+1F0B4", icon: GiCard4Hearts },
  { name: "3 of Hearts", shortCode: "3H", suit: "Hearts", value: 3, unicode: "🂳", unicodeText: "U+1F0B3", icon: GiCard3Hearts },
  { name: "2 of Hearts", shortCode: "2H", suit: "Hearts", value: 2, unicode: "🂲", unicodeText: "U+1F0B2", icon: GiCard2Hearts },

  // Diamonds
  { name: "Ace of Diamonds", shortCode: "AD", suit: "Diamonds", value: 1, unicode: "🃁", unicodeText: "U+1F0C1", icon: GiCardAceDiamonds },
  { name: "King of Diamonds", shortCode: "KD", suit: "Diamonds", value: 13, unicode: "🃎", unicodeText: "U+1F0CE", icon: GiCardKingDiamonds },
  { name: "Queen of Diamonds", shortCode: "QD", suit: "Diamonds", value: 12, unicode: "🃍", unicodeText: "U+1F0CD", icon: GiCardQueenDiamonds },
  { name: "Jack of Diamonds", shortCode: "JD", suit: "Diamonds", value: 11, unicode: "🃋", unicodeText: "U+1F0CB", icon: GiCardJackDiamonds },
  { name: "10 of Diamonds", shortCode: "10D", suit: "Diamonds", value: 10, unicode: "🃊", unicodeText: "U+1F0CA", icon: GiCard10Diamonds },
  { name: "9 of Diamonds", shortCode: "9D", suit: "Diamonds", value: 9, unicode: "🃉", unicodeText: "U+1F0C9", icon: GiCard9Diamonds },
  { name: "8 of Diamonds", shortCode: "8D", suit: "Diamonds", value: 8, unicode: "🃈", unicodeText: "U+1F0C8", icon: GiCard8Diamonds },
  { name: "7 of Diamonds", shortCode: "7D", suit: "Diamonds", value: 7, unicode: "🃇", unicodeText: "U+1F0C7", icon: GiCard7Diamonds },
  { name: "6 of Diamonds", shortCode: "6D", suit: "Diamonds", value: 6, unicode: "🃆", unicodeText: "U+1F0C6", icon: GiCard6Diamonds },
  { name: "5 of Diamonds", shortCode: "5D", suit: "Diamonds", value: 5, unicode: "🃅", unicodeText: "U+1F0C5", icon: GiCard5Diamonds },
  { name: "4 of Diamonds", shortCode: "4D", suit: "Diamonds", value: 4, unicode: "🃄", unicodeText: "U+1F0C4", icon: GiCard4Diamonds },
  { name: "3 of Diamonds", shortCode: "3D", suit: "Diamonds", value: 3, unicode: "🃃", unicodeText: "U+1F0C3", icon: GiCard3Diamonds },
  { name: "2 of Diamonds", shortCode: "2D", suit: "Diamonds", value: 2, unicode: "🃂", unicodeText: "U+1F0C2", icon: GiCard2Diamonds },

  // Clubs
  { name: "Ace of Clubs", shortCode: "AC", suit: "Clubs", value: 1, unicode: "🃑", unicodeText: "U+1F0D1", icon: GiCardAceClubs },
  { name: "King of Clubs", shortCode: "KC", suit: "Clubs", value: 13, unicode: "🃞", unicodeText: "U+1F0DE", icon: GiCardKingClubs },
  { name: "Queen of Clubs", shortCode: "QC", suit: "Clubs", value: 12, unicode: "🃝", unicodeText: "U+1F0DD", icon: GiCardQueenClubs },
  { name: "Jack of Clubs", shortCode: "JC", suit: "Clubs", value: 11, unicode: "🃛", unicodeText: "U+1F0DB", icon: GiCardJackClubs },
  { name: "10 of Clubs", shortCode: "10C", suit: "Clubs", value: 10, unicode: "🃚", unicodeText: "U+1F0DA", icon: GiCard10Clubs },
  { name: "9 of Clubs", shortCode: "9C", suit: "Clubs", value: 9, unicode: "🃙", unicodeText: "U+1F0D9", icon: GiCard9Clubs },
  { name: "8 of Clubs", shortCode: "8C", suit: "Clubs", value: 8, unicode: "🃘", unicodeText: "U+1F0D8", icon: GiCard8Clubs },
  { name: "7 of Clubs", shortCode: "7C", suit: "Clubs", value: 7, unicode: "🃗", unicodeText: "U+1F0D7", icon: GiCard7Clubs },
  { name: "6 of Clubs", shortCode: "6C", suit: "Clubs", value: 6, unicode: "🃖", unicodeText: "U+1F0D6", icon: GiCard6Clubs },
  { name: "5 of Clubs", shortCode: "5C", suit: "Clubs", value: 5, unicode: "🃕", unicodeText: "U+1F0D5", icon: GiCard5Clubs },
  { name: "4 of Clubs", shortCode: "4C", suit: "Clubs", value: 4, unicode: "🃔", unicodeText: "U+1F0D4", icon: GiCard4Clubs },
  { name: "3 of Clubs", shortCode: "3C", suit: "Clubs", value: 3, unicode: "🃓", unicodeText: "U+1F0D3", icon: GiCard3Clubs },
  { name: "2 of Clubs", shortCode: "2C", suit: "Clubs", value: 2, unicode: "🃒", unicodeText: "U+1F0D2", icon: GiCard2Clubs },
];