import {
  GiCardAceSpades,
  GiCardKingSpades,
  GiCardQueenSpades,
  GiCardJackSpades,
  GiCard10Spades,
  GiCard9Spades,
  GiCard8Spades,
  GiCard7Spades,
  GiCard6Spades,
  GiCard5Spades,
  GiCard4Spades,
  GiCard3Spades,
  GiCard2Spades,
  GiCardAceHearts,
  GiCardKingHearts,
  GiCardQueenHearts,
  GiCardJackHearts,
  GiCard10Hearts,
  GiCard9Hearts,
  GiCard8Hearts,
  GiCard7Hearts,
  GiCard6Hearts,
  GiCard5Hearts,
  GiCard4Hearts,
  GiCard3Hearts,
  GiCard2Hearts,
  GiCardAceDiamonds,
  GiCardKingDiamonds,
  GiCardQueenDiamonds,
  GiCardJackDiamonds,
  GiCard10Diamonds,
  GiCard9Diamonds,
  GiCard8Diamonds,
  GiCard7Diamonds,
  GiCard6Diamonds,
  GiCard5Diamonds,
  GiCard4Diamonds,
  GiCard3Diamonds,
  GiCard2Diamonds,
  GiCardAceClubs,
  GiCardKingClubs,
  GiCardQueenClubs,
  GiCardJackClubs,
  GiCard10Clubs,
  GiCard9Clubs,
  GiCard8Clubs,
  GiCard7Clubs,
  GiCard6Clubs,
  GiCard5Clubs,
  GiCard4Clubs,
  GiCard3Clubs,
  GiCard2Clubs,
} from "react-icons/gi";

import { Suit, Rank } from "@/types/cards"; // Adjust path as needed
import { IconType } from "react-icons";

export const bridgeIcons: Record<
  Suit,
  Record<Rank, IconType>
> = {
  [Suit.SPADES]: {
    [Rank.ACE]: GiCardAceSpades,
    [Rank.KING]: GiCardKingSpades,
    [Rank.QUEEN]: GiCardQueenSpades,
    [Rank.JACK]: GiCardJackSpades,
    [Rank.TEN]: GiCard10Spades,
    [Rank.NINE]: GiCard9Spades,
    [Rank.EIGHT]: GiCard8Spades,
    [Rank.SEVEN]: GiCard7Spades,
    [Rank.SIX]: GiCard6Spades,
    [Rank.FIVE]: GiCard5Spades,
    [Rank.FOUR]: GiCard4Spades,
    [Rank.THREE]: GiCard3Spades,
    [Rank.TWO]: GiCard2Spades,
  },
  [Suit.HEARTS]: {
    [Rank.ACE]: GiCardAceHearts,
    [Rank.KING]: GiCardKingHearts,
    [Rank.QUEEN]: GiCardQueenHearts,
    [Rank.JACK]: GiCardJackHearts,
    [Rank.TEN]: GiCard10Hearts,
    [Rank.NINE]: GiCard9Hearts,
    [Rank.EIGHT]: GiCard8Hearts,
    [Rank.SEVEN]: GiCard7Hearts,
    [Rank.SIX]: GiCard6Hearts,
    [Rank.FIVE]: GiCard5Hearts,
    [Rank.FOUR]: GiCard4Hearts,
    [Rank.THREE]: GiCard3Hearts,
    [Rank.TWO]: GiCard2Hearts,
  },
  [Suit.DIAMONDS]: {
    [Rank.ACE]: GiCardAceDiamonds,
    [Rank.KING]: GiCardKingDiamonds,
    [Rank.QUEEN]: GiCardQueenDiamonds,
    [Rank.JACK]: GiCardJackDiamonds,
    [Rank.TEN]: GiCard10Diamonds,
    [Rank.NINE]: GiCard9Diamonds,
    [Rank.EIGHT]: GiCard8Diamonds,
    [Rank.SEVEN]: GiCard7Diamonds,
    [Rank.SIX]: GiCard6Diamonds,
    [Rank.FIVE]: GiCard5Diamonds,
    [Rank.FOUR]: GiCard4Diamonds,
    [Rank.THREE]: GiCard3Diamonds,
    [Rank.TWO]: GiCard2Diamonds,
  },
  [Suit.CLUBS]: {
    [Rank.ACE]: GiCardAceClubs,
    [Rank.KING]: GiCardKingClubs,
    [Rank.QUEEN]: GiCardQueenClubs,
    [Rank.JACK]: GiCardJackClubs,
    [Rank.TEN]: GiCard10Clubs,
    [Rank.NINE]: GiCard9Clubs,
    [Rank.EIGHT]: GiCard8Clubs,
    [Rank.SEVEN]: GiCard7Clubs,
    [Rank.SIX]: GiCard6Clubs,
    [Rank.FIVE]: GiCard5Clubs,
    [Rank.FOUR]: GiCard4Clubs,
    [Rank.THREE]: GiCard3Clubs,
    [Rank.TWO]: GiCard2Clubs,
  },
};
